### ISSUE TITLE
cdtime issue exception that seem to have no base class (python2 maybe 3)

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdtime#10]
In python 2 for sure, didn't test in python3
```python
import cdtime
try:
   b = cdtime.reltime(4,"days since YYY-XX))")
except:
    print "Failed"
```

catches the exception properly

BUT

```python
import cdtime
try:
   b = cdtime.reltime(4,"days since YYY-XX))")
except Exception:
    print "Failed"
```

does not capture the exception 

I "think" this is because the exception is raised at the C level and does not inherit from Exception.

This is not a big deal once you know it, but flake8 will complain that you cannot use an `except` statement w/o an Exception type

**Comment by dnadeau4** [comment]
Does not work in python 2 either. 
There is no exception triggered.  The results is wrong.
https://github.com/UV-CDAT/libcdms/blob/master/src/db_util/cdTimeConv.c#L299-L302

**Comment by doutriaux1** [comment]
In vcs and python 2 had to leave it at except alone and it works, except Exception fails

**Comment by doutriaux1** [comment]
It is not urgent still there is a work around, but I would like to figure out the correct way to raise exceptions from C

**Comment by dnadeau4** [comment]
I forgot to check in libcdms.  will push now.  We will need conda-forge to update it.

**Comment by dnadeau4** [comment]
https://github.com/UV-CDAT/libcdms/pull/9
