### ISSUE TITLE
latest cdtime broken on py3

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdtime#16]
```python
        data = os.path.join(self.basedatadir, "coads_climatology.nc")
        f = cdms2.open(data)
        s = f["SST"]
        s.info()
        print(s.getTime().asComponentTime())
```

**Comment by doutriaux1** [comment]
@muryanto1 this is a good example of why we desperately need your nightly checks!

**Comment by muryanto1** [comment]
Hi Charles,

Working on the script to do nightly checks ..as I am typing ☺
Could you give me the link on where to check our nightly builds?

Thanks,
Lina

**Comment by doutriaux1** [comment]
https://github.com/UV-CDAT/uvcdat/wiki/Obtain-UV-CDAT-nightly-packages

**Comment by doutriaux1** [comment]
@dnadeau4 python 2.7 is broken as well. It seems to affect osx only.

**Comment by doutriaux1** [comment]
@dnadeau4 pointed out this not a bug, "months since 0" is not valid anymore which makes sense. Will update test suites to reflect this.
