### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by sashakames** [CDAT/cdtime#24]
>>> import cdtime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libnetcdf.so.11: cannot open shared object file: No such file or directory
>>>

**Comment by dnadeau4** [comment]
I was able to release cdms 3.0.1 last Saturday,  can you give it a try?

- conda install -c conda-forge cdms2

**Comment by sashakames** [comment]
Thank you!
