### ISSUE TITLE
import error - upgrade to openssl-1.1.1?

### ISSUE THREAD

**Issue by sashakames** [CDAT/cdtime#35]
It appears that conda will upgrade openssl to 1.1.1 even though it appears that the requirement is openssl-1.0.2.  The result is:

    import cdtime
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/cdtime/__init__.py", line 8, in <module>
    from .compreltime import *
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/cdtime/compreltime.py", line 2, in <module>
    from . import _cdtime
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Might the dependency be corrected so openssl stays at 1.0.2 or upgrade openssl to 1.1.1?

**Comment by doutriaux1** [comment]
@sashakames which os? Linux?

**Comment by dnadeau4** [comment]
@sashakames can you submit your "conda info" and "conda list"  I did not get this error.

**Comment by dnadeau4** [comment]
@sashakames how did you install cdtime.  I tried different packages and I cannot even install `openssl-1.1.1a`
