### ISSUE TITLE
cdtime conda package version is 2.6.1-UVCDAT

### ISSUE THREAD

**Issue by JimBiardCics** [CDAT/cdtime#5]
@doutriaux1 @dnadeau4 I am trying to update my cmor conda package. When I attempt to do so, conda tells me it is going to to downgrade my cdtime package as:

cdtime:  2.10-np110py27_0              uvcdat               --> 2.6.1-UVCDAT                  uvcdat

This looks like a bad thing. Is it?

**Comment by JimBiardCics** [comment]
cmds2 will be upgraded to 1.10, cmor to 3.2.5, netcdf4 to 1.2.8, and numpy to 1.12.1.

**Comment by durack1** [comment]
@JimBiardCics are you using the correct `cmor` channel? `-c conda-forge -c pcmdi -c uvcdat`? Make sure `pcmdi` channel is in front of the `uvcdat` channel

**Comment by doutriaux1** [comment]
hum... for cdtime it probably doesn't matter. But @durack1 is right use pcmdi channel last. As conda prioritizes channels in order you pass them.
```
-c conda-forge -c uvcdat -c pcmdi
```

**Comment by JimBiardCics** [comment]
@durack1 @doutriaux1 Which comes first? (The chicken or the egg...) In my .condarc file I had, in order:

- pcmdi
- uvcdat
- conda-forge

I just put conda-forge first, and it upgraded cdtime to the conda-forge 2.10 version. That appears to have solved things. Thanks!

**Comment by doutriaux1** [comment]
My advice is to use packages in conda-forge first then look in uvcdat then pcmdi

**Comment by durack1** [comment]
@doutriaux1 the order that I was suggesting is `-c conda-forge -c pcmdi -c uvcdat` ***NOT what you suggested***, and that is because with `uvcdat` before `pcmdi` you're going to hit `CMOR2.9.2` see https://anaconda.org/uvcdat/cmor, whereas the correct channel is https://anaconda.org/pcmdi/cmor/
